# -*- coding: utf-8 -*-
import csv
import io
import json

from odoo import api, fields, models, _


class AiConversation(models.Model):
    _name = "ai.conversation"
    _description = "AI Conversation"
    _order = "write_date desc, id desc"

    name = fields.Char(default=lambda self: _("New Conversation"))
    user_id = fields.Many2one(
        "res.users", default=lambda self: self.env.user, index=True, required=True
    )
    company_id = fields.Many2one("res.company", default=lambda self: self.env.company)
    message_ids = fields.One2many("ai.message", "conversation_id")
    message_count = fields.Integer(compute="_compute_message_count")
    last_message_date = fields.Datetime(compute="_compute_last_message_date", store=True)
    provider_id = fields.Many2one("ai.provider")

    @api.depends("message_ids")
    def _compute_message_count(self):
        for rec in self:
            rec.message_count = len(rec.message_ids)

    @api.depends("message_ids.create_date")
    def _compute_last_message_date(self):
        for rec in self:
            rec.last_message_date = max(
                rec.message_ids.mapped("create_date") or [rec.create_date or fields.Datetime.now()]
            )

    def action_rename_from_first_message(self):
        """Auto-title a conversation from its first user message."""
        for rec in self:
            first = rec.message_ids.filtered(lambda m: m.role == "user")[:1]
            if first:
                title = (first.content or "").strip().splitlines()[0][:60]
                if title:
                    rec.name = title
        return True

    def get_history_for_llm(self, limit=20):
        """Return recent turns as provider-neutral role/content dicts, so the
        model keeps conversational context (relative dates, pronouns, etc.)."""
        self.ensure_one()
        msgs = self.message_ids.sorted("id")[-limit:]
        return [
            {"role": m.role, "content": m.content or ""}
            for m in msgs
            if m.role in ("user", "assistant") and m.content
        ]


class AiMessage(models.Model):
    _name = "ai.message"
    _description = "AI Message"
    _order = "id"

    conversation_id = fields.Many2one(
        "ai.conversation", required=True, ondelete="cascade", index=True
    )
    role = fields.Selection(
        selection=[("user", "User"), ("assistant", "Assistant"), ("system", "System")],
        required=True,
    )
    content = fields.Text()
    # Structured payload for rendering (kpi / table / chart) produced by the engine.
    payload = fields.Text(help="JSON payload for structured rendering (charts, tables).")
    execution_time = fields.Float(string="Execution Time (s)")

    def get_payload(self):
        self.ensure_one()
        if not self.payload:
            return {}
        try:
            return json.loads(self.payload)
        except (ValueError, TypeError):
            return {}

    # ------------------------------------------------------------------
    # Export (§24/§25) -- always from the STORED payload, i.e. the real
    # numbers computed for this answer; nothing is regenerated by the model.
    # ------------------------------------------------------------------
    def _export_sections(self):
        """Normalise the message's visuals into printable [{title, columns, rows}]."""
        self.ensure_one()
        sections = []
        for v in self.get_payload().get("visuals", []):
            vtype = v.get("type")
            title = v.get("title") or (vtype or "Data").title()
            if vtype == "kpi":
                rows = [[i.get("label"), i.get("value")] for i in v.get("items", [])]
                sections.append({"title": title, "columns": ["Metric", "Value"], "rows": rows})
            elif vtype == "table":
                sections.append({"title": title,
                                 "columns": v.get("columns", []),
                                 "rows": v.get("rows", [])})
            elif vtype in ("bar", "line", "pie"):
                labels = v.get("labels", [])
                series = (v.get("series") or [{}])[0]
                data = series.get("data", [])
                mname = series.get("name", "value")
                n = max(len(labels), len(data))
                rows = [[labels[i] if i < len(labels) else "",
                         data[i] if i < len(data) else None] for i in range(n)]
                sections.append({"title": title, "columns": ["Label", mname], "rows": rows})
        return sections

    def _export_csv_bytes(self):
        self.ensure_one()
        buf = io.StringIO()
        writer = csv.writer(buf)
        writer.writerow([_("AI Analyst Export")])
        writer.writerow([_("Answer")])
        writer.writerow([self.content or ""])
        for sec in self._export_sections():
            writer.writerow([])
            writer.writerow([sec["title"]])
            writer.writerow(sec["columns"])
            for row in sec["rows"]:
                writer.writerow(row)
        # utf-8-sig so Arabic opens correctly in Excel.
        return buf.getvalue().encode("utf-8-sig")

    def _export_xlsx_bytes(self):
        """Returns xlsx bytes, or None if xlsxwriter is unavailable."""
        self.ensure_one()
        try:
            import xlsxwriter
        except ImportError:
            return None
        out = io.BytesIO()
        wb = xlsxwriter.Workbook(out, {"in_memory": True})
        ws = wb.add_worksheet("Analysis")
        ws.set_column(0, 0, 32)
        ws.set_column(1, 8, 18)
        f_title = wb.add_format({"bold": True, "font_size": 13})
        f_bold = wb.add_format({"bold": True})
        f_hdr = wb.add_format({"bold": True, "bg_color": "#eef1f5", "border": 1})
        r = 0
        ws.write(r, 0, "AI Analyst Export", f_title); r += 2
        ws.write(r, 0, "Answer:", f_bold); r += 1
        ws.write(r, 0, self.content or ""); r += 2
        for sec in self._export_sections():
            ws.write(r, 0, sec["title"], f_bold); r += 1
            for c, col in enumerate(sec["columns"]):
                ws.write(r, c, col, f_hdr)
            r += 1
            for row in sec["rows"]:
                for c, val in enumerate(row):
                    ws.write(r, c, val)
                r += 1
            r += 1
        wb.close()
        return out.getvalue()
